import { Question, GiftCategory } from '@/types';

export const questions: Question[] = [
  { id: 3, text: "I enjoy reaching out to new people in my church community", giftCategory: "hospitality" },
  { id: 4, text: "I have the ability and desire to teach", giftCategory: "teaching" },
  { id: 6, text: "I am able to relate God's truth to specific situations", giftCategory: "wisdom" },
  { id: 7, text: "I love helping others grow in their faith", giftCategory: "pastoring" },
  { id: 8, text: "I can clearly communicate the truth of salvation", giftCategory: "evangelism" },
  { id: 9, text: "I am good at making critical decisions", giftCategory: "leadership" },
  { id: 10, text: "I am willing to study and prepare for the task of teaching", giftCategory: "teaching" },
  { id: 11, text: "I am sensitive to people who seem to be hurting", giftCategory: "mercy" },
  { id: 12, text: "I have a natural tendency to encourage others", giftCategory: "exhortation" },
  { id: 13, text: "I can delegate and assign meaningful work", giftCategory: "administration" },
  { id: 14, text: "I take action to meet physical and practical needs", giftCategory: "serving" },
  { id: 15, text: "I can lead people who are at different levels of maturity", giftCategory: "leadership" },
  { id: 16, text: "I love meeting needs through sharing my possessions", giftCategory: "giving" },
  { id: 17, text: "I can organize ideas, people, time, and resources effectively", giftCategory: "administration" },
  { id: 18, text: "I am usually able to analyze a situation correctly", giftCategory: "wisdom" },
  { id: 19, text: "I take initiative to help other Christians grow in their faith", giftCategory: "pastoring" },
  { id: 20, text: "I have awareness of the emotions of other people, such as loneliness, pain, fear and anger", giftCategory: "mercy" },
  { id: 21, text: "I am a cheerful giver", giftCategory: "giving" },
  { id: 22, text: "I am able to communicate vision in such a way that others commit to making the vision a reality", giftCategory: "leadership" },
  { id: 23, text: "It makes me happy to do things for people in need", giftCategory: "serving" },
  { id: 24, text: "I am able to make strangers feel at ease", giftCategory: "hospitality" },
  { id: 25, text: "I can easily identify people who need encouragement", giftCategory: "exhortation" },
  { id: 26, text: "I have trained Christians to be more obedient disciples of Christ", giftCategory: "pastoring" },
  { id: 27, text: "I am willing to do whatever it takes to see others come to Christ", giftCategory: "evangelism" },
  { id: 28, text: "I am generous when it comes to giving", giftCategory: "giving" },
  { id: 29, text: "I enjoy entertaining guests in my home", giftCategory: "hospitality" },
  { id: 30, text: "I have been able to make effective and efficient plans for accomplishing the goals of a group", giftCategory: "administration" },
  { id: 31, text: "Fellow Christians often consult me when they are struggling to make difficult decisions", giftCategory: "wisdom" },
  { id: 32, text: "I think about how I can comfort and encourage others in my spheres of influence", giftCategory: "exhortation" },
  { id: 33, text: "I am able to give spiritual direction to others", giftCategory: "pastoring" },
  { id: 34, text: "I am able to present the gospel to those outside the faith in such a way that they come to trust Christ", giftCategory: "evangelism" },
  { id: 35, text: "I have the capacity to understand the feelings of those in distress", giftCategory: "mercy" },
  { id: 36, text: "I have an acute awareness of the physical needs of others", giftCategory: "serving" },
  { id: 37, text: "I am skilled in setting forth positive and precise steps of action", giftCategory: "administration" },
  { id: 38, text: "I explain Scripture in such a way that others understand it", giftCategory: "teaching" },
  { id: 39, text: "I can usually see spiritual solutions to problems", giftCategory: "wisdom" },
  { id: 40, text: "I welcome opportunities to help people who need comfort, encouragement, and counseling", giftCategory: "exhortation" },
  { id: 41, text: "I feel at ease in sharing Christ with nonbelievers", giftCategory: "evangelism" },
  { id: 42, text: "I can influence others to perform to their highest God-given potential", giftCategory: "leadership" },
  { id: 43, text: "I recognize the signs of stress and distress in others", giftCategory: "mercy" },
  { id: 44, text: "I give generously to worthwhile projects and ministries", giftCategory: "giving" },
  { id: 45, text: "I enjoy doing little things that help people", giftCategory: "serving" },
  { id: 46, text: "I can give a clear, uncomplicated presentation", giftCategory: "teaching" },
  { id: 47, text: "I make strangers comfortable in my home", giftCategory: "hospitality" },
];

export const giftDescriptions: Record<GiftCategory, string> = {
  administration: "You have the ability to organize people, tasks, and resources to accomplish goals effectively.",
  evangelism: "You have a passion for sharing the gospel and leading others to faith in Christ.",
  exhortation: "You naturally encourage, comfort, and motivate others in their faith journey.",
  giving: "You joyfully share your resources to support God's work and meet others' needs.",
  hospitality: "You create welcoming environments where people feel valued and at home.",
  leadership: "You can cast vision and guide others toward achieving meaningful goals.",
  mercy: "You are deeply moved by others' suffering and compelled to help ease their pain.",
  pastoring: "You nurture and guide others in their spiritual growth over the long term.",
  serving: "You readily see practical needs and take action to meet them.",
  teaching: "You can explain truth clearly so others understand and can apply it.",
  wisdom: "You can apply spiritual insight to life situations and help others make wise decisions.",
};

export const giftDisplayNames: Record<GiftCategory, string> = {
  administration: "Administration",
  evangelism: "Evangelism",
  exhortation: "Exhortation",
  giving: "Giving",
  hospitality: "Hospitality",
  leadership: "Leadership",
  mercy: "Mercy",
  pastoring: "Pastoring",
  serving: "Serving",
  teaching: "Teaching",
  wisdom: "Wisdom",
};
